name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Navigate to the directory with the Dockerfile
        run: cd ZMA

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          cd ZMA
          docker build -t zma-backend:${{ github.sha }} .

      - name: Tag Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          cd ZMA
          docker tag zma-backend:${{ github.sha }} $DOCKER_USERNAME/zma-backend:latest

      - name: Push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          cd ZMA
          docker push $DOCKER_USERNAME/zma-backend:latest

      - name: Trigger Deploy on Render
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: curl -X POST $RENDER_DEPLOY_HOOK
